"""
check_drift.py — MLOPS-14 / MLOPS-15
Compares recent production inference data against the reference
distribution (monitoring/reference_stats.json) using the Population
Stability Index (PSI) — a standard, interpretable drift metric:

    PSI < 0.1         -> no significant drift
    0.1 <= PSI < 0.2  -> moderate drift, worth watching
    PSI >= 0.2        -> significant drift, retraining recommended

Exits with code 1 (and writes drift_detected=true to $GITHUB_OUTPUT, if
running in GitHub Actions) when any feature's PSI crosses DRIFT_THRESHOLD,
which the retraining workflow uses to decide whether to trigger MLOPS-15.

NOTE: production data is currently loaded from a local CSV
(monitoring/simulated_production_data.csv), generated by
monitoring/simulate_production_data.py. This is a deliberate
simplification: fetching real collected traffic from the endpoint's
data_collector requires locating the exact blob path Azure ML writes to,
which could not be confirmed in the time available. The data_collector
is still enabled on the champion deployment (see champion-deployment.yaml)
so real traffic can be swapped in later by replacing load_production_data().
"""

import argparse
import json
import os
import sys

import numpy as np
import pandas as pd

DRIFT_THRESHOLD = 0.2


def compute_psi(reference_proportions, current_counts):
    """PSI = sum((current% - reference%) * ln(current% / reference%)) per bin."""
    current_total = sum(current_counts)
    if current_total == 0:
        return 0.0

    psi = 0.0
    for ref_p, cur_count in zip(reference_proportions, current_counts):
        cur_p = cur_count / current_total
        # Avoid log(0) / division by zero on empty bins
        ref_p = max(ref_p, 1e-6)
        cur_p = max(cur_p, 1e-6)
        psi += (cur_p - ref_p) * np.log(cur_p / ref_p)
    return psi


def load_production_data(production_file):
    if not os.path.exists(production_file):
        print(f"No production data file found at {production_file}.")
        return None
    return pd.read_csv(production_file)


def write_github_output(drift_detected: bool):
    """Writes drift_detected=true/false to $GITHUB_OUTPUT for the workflow to read."""
    github_output = os.getenv("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"drift_detected={'true' if drift_detected else 'false'}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference-file", default="monitoring/reference_stats.json")
    parser.add_argument(
        "--production-file", default="monitoring/simulated_production_data.csv"
    )
    args = parser.parse_args()

    with open(args.reference_file) as f:
        reference = json.load(f)

    prod_df = load_production_data(args.production_file)

    if prod_df is None or len(prod_df) == 0:
        print("No production data to check. Exiting without flagging drift.")
        write_github_output(False)
        sys.exit(0)

    drifted_features = []
    for feature_name, ref in reference.items():
        if feature_name not in prod_df.columns:
            continue
        bin_edges = ref["bin_edges"]
        counts, _ = np.histogram(prod_df[feature_name], bins=bin_edges)
        psi = compute_psi(ref["reference_proportions"], counts)

        flag = "DRIFT" if psi >= DRIFT_THRESHOLD else "ok"
        print(f"{feature_name}: PSI={psi:.4f} [{flag}]")

        if psi >= DRIFT_THRESHOLD:
            drifted_features.append((feature_name, psi))

    drift_detected = len(drifted_features) > 0

    if drift_detected:
        print(f"\nDrift detected on {len(drifted_features)} feature(s):")
        for name, psi in drifted_features:
            print(f"  - {name}: PSI={psi:.4f}")
    else:
        print("\nNo significant drift detected.")

    write_github_output(drift_detected)
    sys.exit(1 if drift_detected else 0)


if __name__ == "__main__":
    main()

    